applications:
  flask-app:
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/George-Mikulich/gcp-k8s-terraform
      targetRevision: feature/argocd-terraform
      path: argocd/manifests
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: false
        selfHeal: false
